# 同步与异步

这是 JS 三座大山中的最后一座。在面试时本章节的知识点是重中之重，如果你在面试一个公司时，他们对这方面知识点不进行考察，那么只能说明这个公司的前端很不正规。

### 同步和异步的区别

同步：代码至上而下执行时遇到同步的代码需要先执行完才可以进行下一步任务。

异步：所有需要等待的任务都是异步的。遇到异步代码时，不需要等待而是直接异步任务放入任务队列，等到后面的任务完成后，才会返回来执行没有完成异步的代码。

区别：基于 JS 是一个单线程的语言，同时只能做一件事。同步会阻塞代码执行，异步不会阻塞代码执行。

### 回调地狱是什么？

因为接口、数据、函数之间的依赖关系严重，需要通过一层一层的嵌套回调，导致代码耦合严重、后续难以维护和修改。这种情况称为回调地狱。

### 宏任务和微任务是什么及二者区别？:star2:

- 宏任务：
  - 包括：setTimeout、setInterval、Ajax 和 DOM 事件，以及 node 中的 setImmediate。
- 微任务：
  - 包括：Promise、async/await 以及 node 中的 process.nextTick（微任务中优先级最高的一项）。
- 区别：
  - 微任务和宏任务都为异步，但是微任务的执行时机比宏任务早。
  - 微任务在 DOM 渲染完成之前触发、宏任务在 DOM 渲染完成之后触发。
  - 微任务是 ES6规定的、宏任务是浏览器规定的。

### 浏览器的事件循环是什么？:star2:

1. 同步代码，一行一行放在执行栈中执行
2. 遇到异步任务，会先记录下，等待时机（宏任务和微任务分别记录）
3. 时机到了，就移动到回调队列中
4. 如果执行栈为空，事件循环机制开始工作
5. 会检查微任务队列中是否有事件存在，如果存在则依次执行微任务队列中事件对应的回调，直到微任务队列为空
6. 然后去宏任务队列中取出一个事件，把对应的回调加入当前的执行栈中，当执行栈中当前宏任务执行完毕后，检查微任务队列中是否事件存在
7. 然后继续轮询查找

### Node 的事件循环是什么？:star2:

Node 的事件循环与浏览器的事件循环是完全不相同的。 Node.js采用V8作为js的解析引擎，而I/O处理方面使用了自己设计的 libuv，libuv 是一个基于事件驱动的跨平台抽象层，事件循环机制也是它里面的实现。

- Node 也是单线程，相对浏览器多一个微任务 process.nextTick，一个宏任务 setImmediate。
  - process.nextTick 的回调和 promise 的回调都是微任务，但是 process.nextTick 的回调会比 promise 的先执行
  - setImmediate 是宏任务，但是和其它宏任务一起执行时得到的结果却可能是不确定的.
- **执行阶段：** 在同步代码执行完毕后有以下几个阶段。
  1. timers 阶段：执行 setTimeout() 和 setInterval() 的回调函数。
  2. I/O callbacks 阶段：执行延迟到下一个循环的 I/O 回调。（也就是除了 setTimeout、setInterval、setImmediate、socket 的回调函数）
  3. idle、prepare 阶段：仅 libuv 系统内部调用。
  4. Poll 阶段：轮询的阶段

  - 如果 poll 队列不为空，会检索并执行新的 I/O 回调事件。
  - 如果为空：
    - 若调用了 setImmediate() 就结束 poll 阶段，直接进入 check 阶段。
    - 如果没有调用setImmediate()，就会等待，等待新的回调I/O事件的到来，然后立即执行
    - 如果脚本没有调用了setImmediate()，并且poll队列为空的时候，事件循环将检查哪些计时器 timer 已经到时间。 如果一个或多个计时器 timer
      准备就绪，则事件循环将返回到计时器阶段，以执行这些计时器的回调，这也相当于开启了新一次的循环（tick）

  5. check 阶段：在这个阶段执行 setImmediate() 的回调函数
  6. close callbacks 阶段：执行关闭请求的回调函数，比如 socket.on('close', ...)

```javascript
// 下属两段代码执行的结果都是 3 2 1，可见 process.nextTick 的执行时机要比其它微任务早
Promise.resolve().then(() => console.log(1));
process.nextTick(() => console.log(2));
console.log(3);

process.nextTick(() => console.log(2));
Promise.resolve().then(() => console.log(1));
console.log(3);
```

### 为什么 setTimeout 和 setImmediate 执行顺序是不同的?

```javascript
// 多次执行这段代码，会发现输出结果是不同的
setTimeout(() => console.log(1));
setImmediate(() => console.log(2));
```

<img src="/image/JS/setImmediate.png" width = "600" height = "200" />    

照理来说，setTimeout 在 timers 阶段，并且它回调执行的 delay 参数是0，而 setImmediate 在 check 阶段。 但是 nodejs 官网关于 setTimeout 的定义有这样一句话：_When
delay is larger than 2147483647 or less than 1, the delay will be set to 1. Non-integer delays are truncated to an
integer._

也就是说，下面这两个表达式是等价的：

```javascript
setTimeout(() => console.log(1), 0);
setTimeout(() => console.log(1), 1);
```

而实际执行的时候，进入事件循环以后，有可能到了1ms，也有可能还没到，这取决于系统当时的状况。如果没到1ms，就会跳过 timers，向下执行，到了 check，先执行 setImmediate，然后再在下一次循环中执行
setTimeout。   
但是对于下面的代码，一定会先打印2，再打印1

```javascript
const fs = require('fs');

fs.readFile('test.js', () => {
  setTimeout(() => console.log(1));
  setImmediate(() => console.log(2));
});
```

它的执行过程是会先跳过 timers 阶段，回调直接进入 I/0 callback，然后向下执行，到了 check 阶段执行 setImmediate，然后才在下一次循环的 timers 执行 setTimeout。

### 什么是 promise？为什么叫 promise？

promise 是异步编程的一种解决方案：从语法上讲，promise 是一个对象，从它可以获取异步操作的消息；从本意上讲它被翻译为期约，它约定过一段时间会给你一个结果。

promise 有三种状态：pending（等待态），fulfilled（成功态），rejected（失败态）。状态一旦改变，就不会再变。创造 promise 实例后，它会立即执行。

### promise 的三种状态，如何变化？:star2:

- **三种状态：**
  - pending：进行中的状态，还没有结果
  - fulfilled/resolved：成功的状态
  - rejected：失败的状态
- **状态之间的变化：**
  - promise 之间状态的改变是不可逆的
  - pending 状态可以变化为 fulfilled 状态，也可以变化为 rejected 状态
  - pending 状态不会触发 then 和 catch 回调
  - fulfilled 状态会触发 后续的 then 回调
  - rejected 状态会触发 后续的 catch 回调
- **then 和 catch 对状态对影响（注意这点，很重要）**
  - then 正常返回 fulfilled 状态的 promise，里面有报错则返回 rejected 状态的 promise。
  - catch 正常返回 fulfilled 状态的 promise，里面有报错则返回 rejected 状态的 promise。

下面看几道题，我们对 promise 的变化相关知识点进行下巩固：

```javascript
// p1 的 then 中正常返回没有报错，返回 fulfilled 状态的 promise
const p1 = Promise.resolve().then(() => {
  return 1
});
console.log(p1); // 此时 p1 的状态由 pending 变成 fulfilled
// fulfilled 状态触发 then 的回调
p1.then(() => {
  console.log(1.1) // 1.1 then 被执行 
}).catch(() => {
  console.log(1.2)
});
```

```javascript
// p2 的 then 里面有报错，返回 rejected 状态的 promise
const p2 = Promise.resolve().then(() => {
  throw new Error('err')
});
console.log(p2); // 此时 p2 的状态由 pending 变成 rejected
// rejected 状态触发 catch 回调
p2.then(() => {
  console.log(2.1);
}).catch(() => {
  console.log(2.2); // 2.2 catch 被执行
})
```

```javascript
// p3 的 catch 中正常返回没有报错，返回 fulfilled 状态的 promise
const p3 = Promise.reject().catch((err) => {
  console.log(err)
});
console.log(p3); // 此时 p3 的状态由 pending 变成 fulfilled
// fulfilled 状态触发 then 回调
p3.then(() => {
  console.log(3.1) // 3.1  then 被执行
}).catch(() => {
  console.log(3.2)
})
```

```javascript
// p4 的 catch 里面有报错，返回 rejected 状态的 promise
const p4 = Promise.reject().catch((err) => {
  throw new Error(err)
});
console.log(p4); // 此时 p4 的状态由 pending 变成 rejected
// rejected 状态触发 catch 回调
p4.then(() => {
  console.log(4.1)
}).catch(() => {
  console.log(4.2) // 4.2 catch 被执行
})
console.log(p4); // 此时 p4 状态还是 rejected，因为状态之间的改变是不可逆的。 
```

特殊情况1

```javascript
// 1 3
Promise.resolve().then(() => {
  console.log(1) // 1 并且没有报错会触发后续的 then
}).catch(() => {
  console.log(2) // 1 中没有报错，不会被触发
}).then(() => {
  console.log(3) // 3 被1触发
})
```

特殊情况2

```javascript
// 1 2 4
Promise.resolve().then(() => {
  throw new Error('1') // 1 有报错会触发后续的 catch
}).catch(() => {
  console.log(2) // 2 被1的报错触发
}).catch(() => {
  console.log(3) // 2 中没有报错，不会被触发
}).then(() => {
  console.log(4) // 4 被2触发
})
```

特殊情况3

```javascript
Promise.reject().catch(() => {
  console.log(1) // 1 没有报错会触发后续的 then
}).catch(() => {
  console.log(2) // 1 中没有报错，不会被触发
}).then(() => {
  console.log(3); // 3 被1触发
  throw new Error('4') // 有报错后触发后续的 catch
}).catch(() => {
  console.log(5) // 5 被4的报错触发 
})
```

### async/await 是什么？

async/await 只是一个语法糖，使用同步的语法，彻底消灭调回调函数的终极武器。

JS 还是单线程，还需要异步，它的实现还是基于 eventLoop 的

### async/await 相对于 Promise 的优劣和选择？:star2:

- 优势：
  - 相对于 Promise 能够好的处理 then 的链式调用。（Promise 的链式调用的方式仍然是基于回调函数；async/await 是同步语法，彻底消灭回调函数。）
  - 在处理中间值 Promise 传递参数太麻烦。（每一个步骤都需要使用前一步的结果时难以维护）
- 劣势：
  - 不支持异步并行，多个异步代码之间不存在依赖关系时，后者仍需要等待前者完成。
  - 不支持异步竞速，多个接口有一个返回值时即认为完成请求。（类似 Promise.race() 方法。）
- 两者使用和场景：
  - 要执行多个异步任务，并且这些异步任务有前后依赖的关系，使用 async/await。
  - 要执行多个异步任务，但是这些异步任务没有依赖关系，使用 promise。
  - 执行多个异步任务，同时某个异步任务又返回值即认为成功，使用 promise。

### Promise 构造函数是同步还是异步，then方法呢？

promise 构造函数是同步执行的，then 和 catch 方法是异步执行的。

我们通过一道题目来巩固一些这里面的精髓。

```javascript
// 执行结果是：124536，注意初始化 new Promise 时，传入的函数会立即被执行，then 和 catch 才是异步。
const promise = new Promise((resolve, reject) => {
  console.log(1);
  resolve(5);
  console.log(2);
}).then(val => {
  console.log(val);
});

promise.then(() => {
  console.log(3);
});

console.log(4);

setTimeout(function () {
  console.log(6);
});
```

### Promise 和 async/await 之间的关系？:star2:

- Promise 和 async/await 是相辅相成的关系。（二者不可相互替代）
- 执行 async 函数，返回的是 Promise 对象，如果返回的是一个非 Promise 对象，会自动转。
- 如果 await 后跟着的不是一个 Promise 对象，会自动转。
- await 相当于 Promise 的 then。
- 使用 try...catch 可以捕获异常，代替了 Promise 的 catch。

```javascript
async function fn1 () {
  // 执行 async 函数，返回的是 Promise 对象，如果返回的是一个非 Promise 对象，会自动转。
  return 100
}

const res1 = fn1();
res1.then(data => {
  console.log(fn1()); // promise 对象
  console.log(data); // 100 
});

!(async function () {
  // await 相当于 Promise 的 then。
  const res2 = await fn1();
  console.log(res2); // 100
})();

!(async function () {
  // 如果 await 后跟着的不是一个 Promise 对象，会自动转。
  const res3 = await 100; // 相当于 await Promise.resolve(100)
  console.log(res3);
})()
```

try-catch 相关

```javascript
!(async function () {
  const p1 = Promise.reject('err1');
  try {
    const res1 = await p1;
    console.log(res1);
  } catch (err) {
    console.log(err) // 走到 catch
  }
})();

!(async function () {
  const p2 = Promise.reject('err2');
  const res1 = await p2;
  console.log(res1); // 不会走进来，在上一步直接报错
})()
```

### async/await、setTimeout、Promise 叠加执行输出问题？:star2:

这种题型在面试中经常会出现，也有很多陷阱。我们通过下面的两道题来熟悉下，在实际的面试中大概会出现什么类型的题目。

在做题前注意几点：

- await 同行的是先执行后面的内容，然后变成异步
- 微任务要早于宏任务
- 以及我们提到的 process.nextTick 的执行时机

```javascript
async function async1 () {
  console.log('async1 start'); // 2
  await async2(); // 先执行 async2 再执行 await，后面的变为异步回调
  console.log('async1 end'); // 7
}

async function async2 () {
  console.log('async2'); // 3
}

console.log('script start'); // 1

// 宏任务的异步挂起，最后执行
setTimeout(function () {
  console.log('setTimeout') // 9
  new Promise(function (resolve) { 
    console.log('promise3')
    resolve()
  }).then(function (value) { 
    console.log('promise4')
  })
});

setTimeout(function () {
  console.log('setTimeout2')
  new Promise(function (resolve) {
    console.log('promise5')
    resolve()
  }).then(function (value) {
    console.log('promise6')
  })
}, 1000)

setTimeout(function () {
  console.log('setTimeout3')
  new Promise(function (resolve) {
    console.log('promise7')
    resolve()
  }).then(function (value) {
    console.log('promise8')
  })
})

async1();

new Promise(function (resolve) {
  console.log('promise1'); // 4
  resolve();
  // Promise.then 后面的内容是异步微任务
}).then(function () {
  console.log('promise2'); // 8
});

console.log('script end'); // 5

process.nextTick(function () {
  console.log('node nextTick') // 6
})
```

```javascript
async function async1 () {
  console.log('async1 start'); // 2
  // await 同行的是先之后后面的，再执行 await 变为异步
  await async2();
  // await 后面的内容都可以看作为异步
  console.log('async1 end'); // 5
  await async3();
  // await 后面的内容都可以看作为异步
  console.log('async1 end2'); // 7
}

async function async2 () {
  console.log('async2'); // 3
}

async function async3 () {
  console.log('async3'); // 6
}

console.log('script start'); // 1
// 立即执行
async1();
console.log('script end'); // 4
```

上述这两道题难度是有一些的，如果你第一次没有做出来没有关系，请在对同步和异步相关的知识再精心阅读几遍。

同时在上面两个题目上还可以有很多的变种，我们可以自己对其尝试变化，比如在微任务的外层包一层宏任务等......大家自行尝试，比如下面这道题

```javascript
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1);
    throw new Error();
  }, 2000);
});
const p2 = p1
  .then((val) => {
    console.log(val);
    return val + 1;
  })
  .catch((err) => {
    console.log(err);
    return err;
  });
Promise.all([p2, Promise.reject(3)])
  .then((val2) => {
    console.log(val2);
  })
  .catch((err2) => {
    console.log(err2);
  });
```

### forEach、for...in 和 for...of 的区别？

你可能会好奇，为什么同步异步章节中会出现循环的方法呢？带着你的好奇接着往下看吧。

- forEach 是常规的同步循环
- for...of、for...in 用于异步遍历，循环数组使用 for...of，循环对象使用 for...in。

我们想要每隔一秒，循环打印数组中数字的平方。注意看下边使用不同方法进行循环时，输出结果大概是什么样的。

```javascript
function muti (num) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(num * num)
    }, 1000)
  })
}

const arrs = [1, 2, 3];

// 使用 forEach 循环时，console 会一起出来
arrs.forEach(async function (item) {
  const res = await await muti(item);
  console.log(res);
});

// for...in 是用来循环对象的，不建议循环数组。在这里仅用来演示而已
// 使用 for...in 循环和 for...of 循环，console 会和预期一样。
(async function () {
  for (let i in arrs) {
    const res = await await muti(arrs[i]);
    console.log(res);
  }
})();

(async function () {
  for (let i of arrs) {
    const res = await await muti(i);
    console.log(res);
  }
})();
```

### 前端使用异步的场景？

网络请求：如发送 ajax 请求数据

定时任务：如 setTimeOut，setInterval

### 如何限制 Promise 请求并发数

通过维护一个请求队列，设置当前请求数和最大限制，当请求数小于限制，继续发送请求；当请求数大于限制时，将请求压入请求队列。当一个请求收到响应后，在请求队列头弹出一个请求发送。
